stages:
  - test
  - build
  - upload
  - release
  - predelivery

include:
  - template: Jobs/Secret-Detection.gitlab-ci.yml

variables:
  PACKAGE_VERSION : $CI_COMMIT_TAG
  PAYLINE_ZIP_PACKAGE: "woocommerce-payline-v${PACKAGE_VERSION}.zip"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/woocommerce-payline-release/${PACKAGE_VERSION}"

# Cache for dependencies
cache:
  paths:
    - node_modules/

#######
# Build
#######
build_job:
  stage: build
  image: node:20-buster
  script:
    - npm install
    - npm run build:webpack
    - npm run release:gitlab
    - mv payline.zip $PAYLINE_ZIP_PACKAGE
  artifacts:
    paths:
      - $PAYLINE_ZIP_PACKAGE
    expire_in: 1 hour
  rules:
    - if: $CI_COMMIT_TAG

upload:
  stage: upload
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - build_job
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file $PAYLINE_ZIP_PACKAGE "${PACKAGE_REGISTRY_URL}/${PAYLINE_ZIP_PACKAGE}"

# Release stage
release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "Creating release $CI_COMMIT_TAG"
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - upload
  release:
    name: "Release $CI_COMMIT_TAG "
    description: "For additionnal information please read the CHANGELOG."
    tag_name: $CI_COMMIT_TAG
    ref: $CI_COMMIT_SHA
    assets:
      links:
        - name: woocommerce-payline-$CI_COMMIT_TAG (zip)
          url: "${PACKAGE_REGISTRY_URL}/${PAYLINE_ZIP_PACKAGE}"
          link_type: package

phpunit:
  stage: test
  image: php:${PHP_VERSION}-cli
  # run the job in parallel for each PHP version
  parallel:
    matrix:
#      - PHP_VERSION: "7.2" #no fonctionnel pour l'instant
      - PHP_VERSION: "7.4"
      - PHP_VERSION: "8.0"
      - PHP_VERSION: "8.1"
      - PHP_VERSION: "8.2"
      - PHP_VERSION: "8.3"
      - PHP_VERSION: "8.4"

  variables:
    # put composer cache inside project to improve portability on shared runners
    COMPOSER_CACHE_DIR: "$CI_PROJECT_DIR/.composer/cache"

  cache:
    key: "${CI_JOB_NAME}-${PHP_VERSION}-${CI_COMMIT_REF_SLUG}"
    paths:
      - vendor/
      - .composer/cache/

  before_script:
    # install system deps and PHP extensions commonly used by PHPUnit/WordPress/WooCommerce projects
    - apt-get update -yqq
    - apt-get install -y --no-install-recommends git unzip libicu-dev libonig-dev libzip-dev zlib1g-dev libxml2-dev curl
    - docker-php-ext-configure zip --with-libzip || true
    # install soap as well (nécessaire pour monext/payline-sdk)
    - docker-php-ext-install -j$(nproc) intl mbstring xml zip soap || true
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer --version
    - composer install --prefer-dist --no-progress --no-interaction

  script:
    # run your unit tests; the job (and pipeline) will fail if phpunit exits non-zero
    - ./vendor/bin/phpunit --colors=always

  rules:
    # Run pipeline when a Merge Request is created/updated (GitLab MR ~ GitHub PR)
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: on_success
    # never run by default for other pipeline sources (adjust if you want pushes too)
    - when: never

#######
# Scans
#######
dependency-track-sbom:
  stage: predelivery
  image:
    name: composer:2.6
    entrypoint: [""]
  variables:
    BOM_FILE: "bom.xml"
  before_script:
    - apk add --no-cache libxml2-dev
    - docker-php-ext-install soap
    - composer install --no-interaction --no-progress
  script:
    - echo "Generating CycloneDX SBOM..."
    - composer CycloneDX:make-sbom --output-format xml --output-file $BOM_FILE
    - echo "Uploading BOM to Dependency-Track..."
    - |
      curl -X "POST" "https://dtapi.dgarde.tbdgroup.dev/api/v1/bom" \
      -H "Content-Type: multipart/form-data" \
      -H "X-Api-Key: ${DTRACK_API_KEY}" \
      -F "autoCreate=true" \
      -F "isLatest=true" \
      -F "projectName=${CI_PROJECT_NAME}" \
      -F "projectVersion=${CI_COMMIT_TITLE}" \
      -F "bom=@${BOM_FILE}"
      #-F "project=$PROJECT_UUID" \
      #for projetVersion, can be used : $CI_COMMIT_TITLE, $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME, $CI_MERGE_REQUEST_TITLE
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_BRANCH == "predelivery"'
#  when: manual

sonarqube-scan:
  stage: predelivery
  image:
    name: sonarsource/sonar-scanner-cli:10
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  cache:
    policy: pull-push
    key: "sonar-cache-$CI_COMMIT_REF_SLUG"
    paths:
      - "${SONAR_USER_HOME}/cache"
      - sonar-scanner/
  script:
    - |
      sonar-scanner \
      -Dsonar.host.url="${SONAR_HOST_URL}" \
      -Dsonar.projectKey="${SONAR_PROJECT_KEY}" \
      -Dsonar.projectVersion="${CI_COMMIT_TITLE}" \
      -Dsonar.token="${SONAR_TOKEN}"
      #for projetVersion, can be used : $CI_COMMIT_TITLE, $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME, $CI_MERGE_REQUEST_TITLE
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_BRANCH == "predelivery"'
#  when: manual

secret_detection:
  stage: predelivery
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_BRANCH == "predelivery"'
#  when: manual