sonar.sources=.
sonar.language=php
; Could be nice to add code coverage configuration
; sonar.php.coverage.reportPaths=coverage.xml
sonar.qualitygate.wait=true
sonar.sourceEncoding=UTF-8
sonar.exclusions=vendor/**,node_modules/**,tests/**