name: Generate ZIP file

on:
  workflow_dispatch:
  workflow_call:

jobs:
  generate-zip-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node version
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Generate ZIP file
        run: npm run build && rm -rf ./woocommerce-gateway-payline && unzip woocommerce-gateway-payline.zip -d ./woocommerce-gateway-payline

      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v4
        with:
          name: woocommerce-gateway-payline
          path: woocommerce-gateway-payline/


# https://github.com/woocommerce/woocommerce-paypal-payments/   [NO tasks JS]
# https://github.com/woocommerce/woocommerce-gateway-payfast/   [NO tasks JS]
# https://github.com/woocommerce/woocommerce-gateway-stripe/    [tasks JS]
# https://github.com/Automattic/woocommerce-payments            [tasks JS]