name: Build for release

on:
#  release:
#    types:
#      - created  # Déclenchement lors de la création d'une release
  push:
    branches:
      - github_action

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Setup node version
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build && rm -rf ./release/payline && unzip woocommerce-gateway-payline.zip -d ./release/payline

      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v4
        with:
          name: payline
          path: ./release/
          retention-days: 1