name: Build for release

#on:
#  push:
#    tags:
#      - '*'
#    branches:
#      - github_action
#  release:
#    types: [created]  # Déclenchement lors de la création d'une release

# Ce workflow peut être déclenché manuellement
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Nom du tag à créer'
        required: true
        default: 'v1.0.0'
      release_name:
        description: 'Nom de la release'
        required: true
        default: 'Version 1.0.0'
      release_body:
        description: 'Description de la release'
        required: false
        default: 'Changelog de la version.'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

#      - name: Setup node version
#        uses: actions/setup-node@v4
#        with:
#          node-version-file: '.nvmrc'
#
#      - name: Install dependencies
#        run: npm install
#
#      - name: Build project
#        run: npm run build
#
#      - name: List files
#        run: ls -lisa
#
#      - name: Zip fix
#        run: rm -rf ./release && mkdir release && unzip woocommerce-gateway-payline.zip -d ./release/payline
#
#      - name: Use the Upload Artifact GitHub Action
#        uses: actions/upload-artifact@v4
#        with:
#          name: woocommerce-payline-v
#          path: ./release
#          retention-days: 1

#      # 3. Créer une release associée au tag
#      - name: Create GitHub Release
#        uses: actions/create-release@v1
#        with:
#          tag_name: ${{ inputs.tag_name }}
#          release_name: ${{ inputs.release_name }}
#          body: ${{ inputs.release_body }}
#          draft: false
#          prerelease: false

      - uses: ncipollo/release-action@v1
        name: Create GitHub Release ncipollo
        with:
          name: ${{ inputs.release_name }}
          tag: ${{ inputs.tag_name }}
          bodyFile: ${{ inputs.release_body }}
          prerelease: true